### ISSUE TITLE
any upload image size limit ?

### ISSUE THREAD

**Issue by whtsang22** [illucIT/primefaces-imageeditor#1]
Dear Sir,

I am trying this component and it works really great.
However, for some image I encounter upload problem.
The image file I edit is around 700K and toDataURL got approx 4M.
Just wonder is there any limits on the upload image size and any setting to increase it ?

Thx alots.

**Comment by metaxmx** [comment]
Hi, 

There is indeed a limit for the file size, as the data of the image has to be sent to the server in a single HTTP Post request.
Most application servers have a limit of byte which are allowed to be sent in a POST request. E.g. for Apache Tomcat this limit is 2MB, and for Wildfly it is usually 10MB. If you known that you want to upload more data at once, you can configure this settings on your application server.

For Apache Tomcat, add the parameter `httpPostSize` to the <Connector> in `conf/server.xml` with the maximum number of bytes allowed, e.g. for 20MB (= 20971520 Bytes):

```
<Connector executor="tomcatThreadPool" port="8080"
    protocol="HTTP/1.1" connectionTimeout="20000"
    redirectPort="8443" maxPostSize="20971520" />
```

For Wildfly, add the parameter `max-post-size` to the HTTP-Listener in the undertow subsystem in your `standalone.xml`, e.g.:

```
<subsystem xmlns="urn:jboss:domain:undertow:1.1">
    <server name="default-server">
        <http-listener name="default" socket-binding="http" max-post-size="20971520" />
        <host name="default-host" alias="localhost">
            ...
        </host>
    </server>
    ....
</subsystem>
```

If you have any other application server or servlet container, I'm sure there will be a similar setting in the configuration.

Just a comment to the file size: although the original image might be smaller (like in your example), the image data will be delivered in Base64 encoding to the server (to avoid problems with the request encoding, and for a better handling of the binary), and also the image will be exported as JPEG image with the highest image quality, which might in combination result in a bigger data size to be transported.

I hope this will help you. If you have further remarks or questions, please feel free to ask.

Best regards,
Christian

**Comment by whtsang22** [comment]
Dear Christian, 

Really thanks for the help. The problem is now solved.
I following your advised and update tomee server.xml :
    <Connector port="8086" protocol="AJP/1.3" redirectPort="443"
       connectionTimeout="60000" maxPostSize="20971520" />
    <Connector port="80" protocol="HTTP/1.1" redirectPort="443"
       connectionTimeout="60000" maxPostSize="20971520" />

Btw, I have another question, I am using tomee server which use myfaces-impl intead of Mojarra.
Hence it miss:
"com.sun.faces.facelets.compiler.UILiteralText (@ ImageEditorComponentHandler )"

Currently, I mask it off but wonder is there another class for substituting it.

Best regards,
Hong Tsang.

**Comment by metaxmx** [comment]
Hi,

You are right, the used class `UILiteralText` is an internal Mojarra class and not part of the JSF standard.
I replaced this class (used for literal HTML output rendering) by the component `HtmlOutputText` (which is also used if you type `<h:outputText />` in a JSF file) for direct rendering now.

There is now a new version 1.0.2 of the image editor lib which should not have this problem any more.

Best regards,
Christian

**Comment by whtsang22** [comment]
Thx alot. It works perfectly.
