### ISSUE TITLE
Primefaces v6+ supporting

### ISSUE THREAD

**Issue by pdelgado84** [illucIT/primefaces-imageeditor#2]
Hi there! I think this tool is very useful for those that use primefaces like me, but its outdated... Could it be possible to have compatibility for PrimeFaces v6.0 and newer versions?
Thanks in advantage.

**Comment by metaxmx** [comment]
Hi,
thank you for your comment!

We will check how big the effort will be for the upgrade to PF6

**Comment by metaxmx** [comment]
I have created a new Version 2.0.0 with Support for Primefaces 6.2 (also tested with the latest Tomcat and JSF 2.3)

```
	<dependency>
		<groupId>com.illucit</groupId>
		<artifactId>primefaces-imageeditor</artifactId>
		<version>2.0.0</version>
	</dependency>
```

If you need a specific older PF version, there is a hint in the readme how to remove the direct dependency and add you own - a assume it should be compatible with the whole 6.x branch.

Please tell me if this works for you

**Comment by pdelgado84** [comment]
Works perfectly! Great job, thank you very much.
